# Setup
title:               piecewise
tagline:             '{ econ / math / cs / finance / ramblings }'
description:         ''
url:                 https://eric-ycw.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Eric Yip
  url:               https://eric-ycw.github.io
  email:             cwericyip@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-last-modified-at

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
